import type { Deal } from "@/types/deals.types";

export const recentBusinesses = [
  {
    id: "1",
    name: "TechFlow SaaS",
    industry: "Technology",
    revenue: "$2.4M",
    askingPrice: "$7.2M",
    location: "San Francisco, CA",
    seller: "Jane Doe",
    match: 94,
    liked: true,
    verified: true,
  },
  {
    id: "2",
    name: "GreenLeaf Consulting",
    industry: "Professional Services",
    revenue: "$1.8M",
    askingPrice: "$4.5M",
    location: "Austin, TX",
    seller: "Mark Wilson",
    match: 87,
    liked: false,
    verified: true,
  },
  {
    id: "3",
    name: "Urban Eats Delivery",
    industry: "Food & Beverage",
    revenue: "$3.1M",
    askingPrice: "$9.3M",
    location: "Chicago, IL",
    seller: "Sarah Kim",
    match: 91,
    liked: true,
    verified: true,
  },
];

export const notifications = [
  {
    id: 1,
    text: "TechFlow SaaS seller wants to connect",
    time: "2h ago",
    type: "match",
  },
  {
    id: 2,
    text: "New business matching your criteria",
    time: "5h ago",
    type: "business",
  },
  {
    id: 3,
    text: "Your offer on GreenLeaf was declined",
    time: "1d ago",
    type: "offer",
  },
  {
    id: 4,
    text: "Document request from Urban Eats",
    time: "2d ago",
    type: "document",
  },
];

export const recentMatches = [
  {
    id: "1",
    name: "Michael Chen",
    company: "Growth Ventures",
    avatar: "",
    budget: "$2M - $5M",
    match: 94,
    lastActive: "2 hours ago",
    status: "interested",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    company: "Tech Acquisitions LLC",
    avatar: "",
    budget: "$1M - $3M",
    match: 87,
    lastActive: "1 day ago",
    status: "viewing",
  },
  {
    id: "3",
    name: "David Rodriguez",
    company: "Strategic Partners",
    avatar: "",
    budget: "$3M - $8M",
    match: 91,
    lastActive: "3 days ago",
    status: "matched",
  },
];

export const mockBuyerProfiles = [
  {
    id: "1",
    name: "Michael Chen",
    company: "Growth Ventures LLC",
    avatar: "",
    location: "San Francisco, CA",
    budget: { min: 2000000, max: 5000000 },
    industries: ["Technology", "SaaS", "E-commerce"],
    experience: "4+ acquisitions",
    timeline: "3-6 months",
    verified: true,
    rating: 4.8,
    totalDeals: 12,
    bio: "Experienced tech entrepreneur and investor focusing on profitable SaaS businesses with strong recurring revenue. Looking for businesses with proven product-market fit and growth potential.",
    lookingFor: ["Recurring Revenue", "Growth Potential", "Strong Team"],
  },
  {
    id: "2",
    name: "Sarah Johnson",
    company: "Strategic Acquisitions Inc",
    avatar: "",
    location: "Austin, TX",
    budget: { min: 1000000, max: 3000000 },
    industries: ["Healthcare", "Professional Services", "Technology"],
    experience: "1-3 acquisitions",
    timeline: "6-12 months",
    verified: true,
    rating: 4.6,
    totalDeals: 5,
    bio: "Former healthcare executive transitioning to business ownership. Particularly interested in service-based businesses with established customer relationships and steady cash flow.",
    lookingFor: [
      "Stable Cash Flow",
      "Established Customer Base",
      "Service Business",
    ],
  },
  {
    id: "3",
    name: "David Rodriguez",
    company: "Rodriguez Family Office",
    avatar: "",
    location: "Miami, FL",
    budget: { min: 3000000, max: 8000000 },
    industries: ["Manufacturing", "Real Estate", "Retail"],
    experience: "Professional investor",
    timeline: "I'm flexible",
    verified: true,
    rating: 4.9,
    totalDeals: 28,
    bio: "Third-generation family business investor with extensive experience in traditional industries. Focused on businesses with strong fundamentals and opportunities for operational improvements.",
    lookingFor: [
      "Traditional Business",
      "Operational Efficiency",
      "Family Values",
    ],
  },
  {
    id: "4",
    name: "Emily Watson",
    company: "Watson Capital Partners",
    avatar: "",
    location: "Chicago, IL",
    budget: { min: 1500000, max: 4000000 },
    industries: ["E-commerce", "Retail", "Consumer Goods"],
    experience: "First-time buyer",
    timeline: "Within 3 months",
    verified: true,
    rating: 4.7,
    totalDeals: 0,
    bio: "E-commerce executive with 15 years of experience building online brands. Ready to acquire my first business and leverage my digital marketing expertise to drive growth.",
    lookingFor: [
      "Digital Business",
      "Growth Opportunity",
      "Marketing Potential",
    ],
  },
];

export const mockDeals: Deal[] = [
  {
    id: "1",
    buyerName: "Michael Chen",
    buyerCompany: "Growth Ventures LLC",
    buyerAvatar: "",
    businessName: "TechFlow SaaS",
    offerAmount: 3200000,
    stage: "diligence",
    progress: 65,
    lastActivity: "2 hours ago",
    nextAction: "Review financial projections",
    documents: { uploaded: 12, required: 18 },
    aiInsights: [
      "Buyer's financing is pre-approved",
      "Timeline is on track for 90-day close",
      "Consider highlighting customer retention metrics",
    ],
  },
  {
    id: "2",
    buyerName: "Sarah Johnson",
    buyerCompany: "Strategic Acquisitions Inc",
    buyerAvatar: "",
    businessName: "TechFlow SaaS",
    offerAmount: 2850000,
    stage: "negotiation",
    progress: 45,
    lastActivity: "1 day ago",
    nextAction: "Respond to price adjustment request",
    documents: { uploaded: 8, required: 18 },
    aiInsights: [
      "Buyer requested 10% price reduction",
      "Consider counter-offer with earnout structure",
      "Similar deals in your industry closed at higher multiples",
    ],
  },
  {
    id: "3",
    buyerName: "David Rodriguez",
    buyerCompany: "Rodriguez Family Office",
    buyerAvatar: "",
    businessName: "TechFlow SaaS",
    offerAmount: 3450000,
    stage: "initial",
    progress: 15,
    lastActivity: "3 days ago",
    nextAction: "Schedule initial meeting",
    documents: { uploaded: 3, required: 18 },
    aiInsights: [
      "High-quality buyer with strong financial backing",
      "Previous deals show fast decision-making",
      "Consider prioritizing this opportunity",
    ],
  },
];

export const stageColors = {
  initial: "bg-[#0D3B66]",
  diligence: "bg-[#F4D35E]",
  negotiation: "bg-[#F95738]",
  closing: "bg-[#048A81]",
  completed: "bg-[#048A81]",
};

export const stageLabels = {
  initial: "Initial Interest",
  diligence: "Due Diligence",
  negotiation: "Negotiation",
  closing: "Closing",
  completed: "Completed",
};
